//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExclusionaryList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppInstListDetail
    {
        public int AppInstListDetailsID { get; set; }
        public int AppInstListID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string State { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<int> AppInstListTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> CreatedByPrsn { get; set; }
    }
}
