//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExclusionaryList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppinstList
    {
        public int AppinstListID { get; set; }
        public string ListName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedDt { get; set; }
        public bool IsDefault { get; set; }
        public int ListTypeID { get; set; }
        public int AppInstId { get; set; }
    }
}
